version: '3.1'

services:
  orderdb:
    image: mysql:latest
    container_name: orderdb-container
    environment:
      MYSQL_ROOT_PASSWORD: orderadmin123
      MYSQL_DATABASE: orderdb
      MYSQL_USER: orderdb
      MYSQL_PASSWORD: orderdb123
    ports:
      - "3306:3306"

  shipmentdb:
    image: mysql:latest
    container_name: shipmentdb-container
    environment:
      MYSQL_ROOT_PASSWORD: shipmentadmin123
      MYSQL_DATABASE: shipmentdb
      MYSQL_USER: shipmentdb
      MYSQL_PASSWORD: shipmentdb123
    ports:
      - "3306:3306"    

  reportdb:
    image: mysql:latest
    container_name: reportdb-container
    environment:
      MYSQL_ROOT_PASSWORD: reportadmin123
      MYSQL_DATABASE: reportdb
      MYSQL_USER: reportdb
      MYSQL_PASSWORD: reportdb123
    ports:
      - "3306:3306"          

  orderapi:
    build:
      context: .  # Specify the path to your API project directory
      dockerfile: OrderDockerfile       # Specify the Dockerfile name if it's different from the default
    container_name: orderservice-container
    depends_on:
      - orderdb
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=orderdb;User=orderdb;Password=orderdb123;"
    ports:
      - "5000:80"

  shipmentapi:
    build:
      context: .  # Specify the path to your API project directory
      dockerfile: ShipmentDockerfile       # Specify the Dockerfile name if it's different from the default
    container_name: shipmentservice-container
    depends_on:
      - shipmentdb
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=shipmentdb;User=shipmentdb;Password=shipmentdb123;"
    ports:
      - "5000:80"

  reportapi:
    build:
      context: .  # Specify the path to your API project directory
      dockerfile: ReportDockerfile       # Specify the Dockerfile name if it's different from the default
    container_name: reportservice-container
    depends_on:
      - reportdb
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=reportdb;User=reportdb;Password=reportdb123;"
    ports:
      - "5000:80"      